# Javascript Node CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.5

    steps:
      - checkout
      - run: yarn
      - run: yarn lint
      - run: echo $CIRCLE_BRANCH
      - run: CI=false yarn deploy $CIRCLE_BRANCH
      - store_artifacts:
          path: build/grid-ui*.zip
      - store_artifacts:
          path: build/manifest.json

  tag-release:
    docker:
      - image: circleci/node:10.5
    steps:
      - run:
          name: 'Start grid build on CircleCI'
          command: |
            curl -X POST --header "Content-Type: application/json" \
            -d '{"branch":"master"}' \
            https://circleci.com/api/v1.1/project/github/ethereum/grid/build?circle-token=$CIRCLE_TOKEN_MIST_BOT

workflows:
  version: 2

  untagged-build:
    jobs:
      - build

  tagged-build:
    jobs:
      - tag-release:
          filters:
            tags:
              only: /^v.+/
            branches:
              ignore: /.+/
